name: flutter_web_admin_template
description: Experiment on Flutter web for Admin dashboard..

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sura_flutter: ^1.2.1
  sura_manager: ^1.4.0
  provider: ^6.0.3
  dio: ^4.0.6
  sentry: ^6.5.1
  go_router: ^3.1.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  ##UI
  fl_chart: ^0.50.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
